apiVersion: apps/v1
kind: Deployment
metadata:
  name: flare-bank-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flare-bank
  template:
    metadata:
      labels:
        app: flare-bank
    spec:
      containers:
        - name: flare-bank
          image: oussamaslimani2001/flare-bank:testing
          ports:
            - containerPort: 80
